### ISSUE TITLE
docker run fails

### ISSUE THREAD

**Issue by laochonlam** [UMass-LIDS/Proteus#1]
Hi,

I am following the instructions from https://github.com/UMass-LIDS/Proteus/blob/main/DOCKER.md.

When I run `docker run -it sohaibahmad759/proteus`, it shows

`WARNING: The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64/v3) and no specific platform was requested`

I tried this from my x86 linux GPU machines and EC2 `t2.micro`, all shows the same error. May I know what architecture or requirement for the machine that I need to use for this? Thank you!

Lam

**Comment by sohaibahmad759** [comment]
Hi Lam,

This issue pertains to the host platform on which you are trying to run the Docker image. The Docker image requires an `arm64` platform, while you are using an `amd64` platform. We have updated the image on the Docker hub to support the `amd64` platform and tested it with the EC2 `t2.micro` instance, so you should be able to run it there now.

Please let us know if you encounter any other issues while running our code. Note that you may have to replace the trial Gurobi license in the `gurobi` folder with your own license.

We appreciate your interest in Proteus! Please consider citing our work if you find it useful.

**Comment by laochonlam** [comment]
Hi @sohaibahmad759 ,

I got it run by the local installation method. Great work, thanks!

Lam
